apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306 # servie port
    targetPort: 3306 # container port