apiVersion: v2 # k8s related api version
name: shipping
version: 0.0.1 # chart version
appVersion: 1.4.0 # application version like cart, catalogue, mysql, etc
description: "installing shipping for roboshop application 1.4.0 version"

