apiVersion: v2 # k8s related api version
name: rabbitmq
version: 0.0.1 # chart version
appVersion: 3.0# application version like cart, catalogue, mysql, etc
description: "installing rabbitmq for roboshop application 3.0 version"

