apiVersion: v2 # k8s related api version
name: redis
version: 0.0.1 # chart version
appVersion: 7.0# application version like cart, catalogue, mysql, etc
description: "installing redis for roboshop application 7.0 version"

